context /yamicuberush/ {
  type                    NULL
  location                /home/villa.linkflow.page/public_html/yamicuberush/
  allowBrowse             1
  indexFiles              index.html
  extraHeaders            <<<END_extraHeaders
unset Cache-control
set Cache-control no-store, no-cache, must-revalidate, max-age=0
set Pragma no-cache
set Expires 0
  END_extraHeaders
}
